<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class GruposPalavrasSeeder extends Seeder {

    public function run(): void {
        DB::table('grupos_palavras')->insert([
            ['id' => 1, 'grupo_id' => 1, 'palavra_id' => 1],
            ['id' => 2, 'grupo_id' => 2, 'palavra_id' => 1],
            ['id' => 3, 'grupo_id' => 3, 'palavra_id' => 1],
            ['id' => 4, 'grupo_id' => 1, 'palavra_id' => 2],
            ['id' => 5, 'grupo_id' => 1, 'palavra_id' => 3],
            ['id' => 6, 'grupo_id' => 1, 'palavra_id' => 4],
            ['id' => 7, 'grupo_id' => 1, 'palavra_id' => 5],
            ['id' => 8, 'grupo_id' => 1, 'palavra_id' => 6],
            ['id' => 9, 'grupo_id' => 1, 'palavra_id' => 7],
            ['id' => 10, 'grupo_id' => 1, 'palavra_id' => 8],
            ['id' => 11, 'grupo_id' => 2, 'palavra_id' => 9],
            ['id' => 12, 'grupo_id' => 2, 'palavra_id' => 10],
            ['id' => 13, 'grupo_id' => 2, 'palavra_id' => 11],
            ['id' => 14, 'grupo_id' => 2, 'palavra_id' => 12],
            ['id' => 15, 'grupo_id' => 2, 'palavra_id' => 13],
            ['id' => 16, 'grupo_id' => 3, 'palavra_id' => 13],
            ['id' => 17, 'grupo_id' => 2, 'palavra_id' => 14],
            ['id' => 18, 'grupo_id' => 2, 'palavra_id' => 15],
            ['id' => 19, 'grupo_id' => 3, 'palavra_id' => 16],
            ['id' => 20, 'grupo_id' => 3, 'palavra_id' => 17],
            ['id' => 21, 'grupo_id' => 3, 'palavra_id' => 18],
            ['id' => 22, 'grupo_id' => 3, 'palavra_id' => 19],
            ['id' => 23, 'grupo_id' => 3, 'palavra_id' => 20],
            ['id' => 24, 'grupo_id' => 3, 'palavra_id' => 21],
            ['id' => 25, 'grupo_id' => 3, 'palavra_id' => 22],
            ['id' => 26, 'grupo_id' => 4, 'palavra_id' => 22],
            ['id' => 27, 'grupo_id' => 4, 'palavra_id' => 23],
            ['id' => 28, 'grupo_id' => 4, 'palavra_id' => 24],
            ['id' => 29, 'grupo_id' => 4, 'palavra_id' => 25],
            ['id' => 30, 'grupo_id' => 4, 'palavra_id' => 26],
            ['id' => 31, 'grupo_id' => 4, 'palavra_id' => 27],
            ['id' => 32, 'grupo_id' => 4, 'palavra_id' => 28],
            ['id' => 33, 'grupo_id' => 5, 'palavra_id' => 29],
            ['id' => 34, 'grupo_id' => 3, 'palavra_id' => 29],
            ['id' => 35, 'grupo_id' => 5, 'palavra_id' => 30],
            ['id' => 36, 'grupo_id' => 5, 'palavra_id' => 31],
            ['id' => 37, 'grupo_id' => 5, 'palavra_id' => 32],
            ['id' => 38, 'grupo_id' => 5, 'palavra_id' => 33],
            ['id' => 39, 'grupo_id' => 5, 'palavra_id' => 34],
            ['id' => 40, 'grupo_id' => 5, 'palavra_id' => 35],
            ['id' => 41, 'grupo_id' => 5, 'palavra_id' => 36],
            ['id' => 42, 'grupo_id' => 6, 'palavra_id' => 37],
            ['id' => 43, 'grupo_id' => 7, 'palavra_id' => 37],
            ['id' => 44, 'grupo_id' => 6, 'palavra_id' => 38],
            ['id' => 45, 'grupo_id' => 7, 'palavra_id' => 38],
            ['id' => 46, 'grupo_id' => 6, 'palavra_id' => 39],
            ['id' => 47, 'grupo_id' => 6, 'palavra_id' => 40],
            ['id' => 48, 'grupo_id' => 6, 'palavra_id' => 41],
            ['id' => 49, 'grupo_id' => 6, 'palavra_id' => 42],
            ['id' => 50, 'grupo_id' => 7, 'palavra_id' => 43],
            ['id' => 51, 'grupo_id' => 7, 'palavra_id' => 44],
            ['id' => 52, 'grupo_id' => 7, 'palavra_id' => 45],
            ['id' => 53, 'grupo_id' => 7, 'palavra_id' => 46],
            ['id' => 54, 'grupo_id' => 8, 'palavra_id' => 47],
            ['id' => 55, 'grupo_id' => 8, 'palavra_id' => 48],
            ['id' => 56, 'grupo_id' => 8, 'palavra_id' => 49],
            ['id' => 57, 'grupo_id' => 8, 'palavra_id' => 50],
            ['id' => 58, 'grupo_id' => 9, 'palavra_id' => 51],
            ['id' => 59, 'grupo_id' => 9, 'palavra_id' => 52],
            ['id' => 60, 'grupo_id' => 9, 'palavra_id' => 53],
            ['id' => 61, 'grupo_id' => 9, 'palavra_id' => 54],
            ['id' => 62, 'grupo_id' => 10, 'palavra_id' => 55],
            ['id' => 63, 'grupo_id' => 10, 'palavra_id' => 56],
            ['id' => 64, 'grupo_id' => 10, 'palavra_id' => 57],
            ['id' => 65, 'grupo_id' => 10, 'palavra_id' => 58],
            ['id' => 66, 'grupo_id' => 11, 'palavra_id' => 59],
            ['id' => 67, 'grupo_id' => 11, 'palavra_id' => 60],
            ['id' => 68, 'grupo_id' => 11, 'palavra_id' => 61],
            ['id' => 69, 'grupo_id' => 11, 'palavra_id' => 62],
            ['id' => 70, 'grupo_id' => 11, 'palavra_id' => 63],
            ['id' => 71, 'grupo_id' => 12, 'palavra_id' => 64],
            ['id' => 72, 'grupo_id' => 13, 'palavra_id' => 64],
            ['id' => 73, 'grupo_id' => 12, 'palavra_id' => 65],
            ['id' => 74, 'grupo_id' => 13, 'palavra_id' => 65],
            ['id' => 75, 'grupo_id' => 12, 'palavra_id' => 66],
            ['id' => 76, 'grupo_id' => 12, 'palavra_id' => 67],
            ['id' => 77, 'grupo_id' => 12, 'palavra_id' => 68],
            ['id' => 78, 'grupo_id' => 12, 'palavra_id' => 69],
            ['id' => 79, 'grupo_id' => 13, 'palavra_id' => 70],
            ['id' => 80, 'grupo_id' => 13, 'palavra_id' => 71],
            ['id' => 81, 'grupo_id' => 13, 'palavra_id' => 72],
            ['id' => 82, 'grupo_id' => 13, 'palavra_id' => 73],
        ]);
    }
}
