<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class GruposSeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        DB::table('grupos')->insert([
            ['id' => 1, 'nome' => 'Advérbios de Lugar', 'disciplina_id' =>  1],
            ['id' => 2, 'nome' => 'Fontes de Energia', 'disciplina_id' =>  1],
            ['id' => 3, 'nome' => 'Participantes num processo judicial', 'disciplina_id' =>  1],
            ['id' => 4, 'nome' => 'Notas Musicais', 'disciplina_id' =>  1],
            ['id' => 5, 'nome' => 'Times de Futebol', 'disciplina_id' =>  1],
            ['id' => 6, 'nome' => 'Bancos', 'disciplina_id' =>  1],
            ['id' => 7, 'nome' => 'Estabelecimentos educacionais', 'disciplina_id' =>  1],
            ['id' => 8, 'nome' => 'Cargos no mercado financeiro', 'disciplina_id' =>  1],
            ['id' => 9, 'nome' => 'Comida', 'disciplina_id' =>  1],
            ['id' => 10, 'nome' => 'Bairros do Rio de Janeiro', 'disciplina_id' =>  1],
            ['id' => 11, 'nome' => 'Temperos', 'disciplina_id' => 1],
            ['id' => 12, 'nome' => 'Internet', 'disciplina_id' => 1],
            ['id' => 13, 'nome' => 'Meios de comunicação obsoletos', 'disciplina_id' => 1],
            ['id' => 14, 'nome' => 'Adjetivos relativos a freqência', 'disciplina_id' => 1],
            ['id' => 15, 'nome' => 'Itens de papelaria', 'disciplina_id' => 1],
            ['id' => 16, 'nome' => 'Cosméticos labiais', 'disciplina_id' => 1],
            ['id' => 17, 'nome' => 'Carnaval', 'disciplina_id' => 1],
            ['id' => 18, 'nome' => 'Ritmos musicais', 'disciplina_id' => 1],
            ['id' => 19, 'nome' => 'Enorme', 'disciplina_id' => 1],
            ['id' => 20, 'nome' => 'Clássicos literários', 'disciplina_id' => 1],
            ['id' => 21, 'nome' => 'Roda (de) ___', 'disciplina_id' => 1],
            ['id' => 22, 'nome' => 'Usados no jardim', 'disciplina_id' => 1],
            ['id' => 23, 'nome' => 'Inteligente', 'disciplina_id' => 1],
            ['id' => 24, 'nome' => 'Pássaros', 'disciplina_id' => 1],
            ['id' => 25, 'nome' => 'Funções de modelos', 'disciplina_id' => 1],
            ['id' => 26, 'nome' => 'Típicos do Rio Grande do Sul', 'disciplina_id' => 1],
            ['id' => 27, 'nome' => 'Sobremesas geladas', 'disciplina_id' => 1],
            ['id' => 28, 'nome' => 'Apóstolos', 'disciplina_id' => 1],
            ['id' => 29, 'nome' => 'Olívias famosas', 'disciplina_id' => 1],
            ['id' => 30, 'nome' => 'Critérios para apuração do carnaval', 'disciplina_id' => 1],
            ['id' => 31, 'nome' => 'Marsupiais', 'disciplina_id' => 1],
            ['id' => 32, 'nome' => 'Instrumentos musicais', 'disciplina_id' => 1],
            ['id' => 33, 'nome' => 'Especiarias', 'disciplina_id' => 1],
            ['id' => 34, 'nome' => 'Reações comuns a picadas de insetos', 'disciplina_id' => 1],
            ['id' => 35, 'nome' => 'Órgãos do corpo humano', 'disciplina_id' => 1],
            ['id' => 36, 'nome' => 'Relacionados a sons', 'disciplina_id' => 1],
            ['id' => 37, 'nome' => 'Ratos de desenhos animados', 'disciplina_id' => 1],
            ['id' => 38, 'nome' => 'Quadrinhos', 'disciplina_id' => 1],
            ['id' => 39, 'nome' => 'Realizados no hospital', 'disciplina_id' => 1],
            ['id' => 40, 'nome' => 'Os/As três ___', 'disciplina_id' => 1],
            ['id' => 41, 'nome' => 'Procedimentos policiais', 'disciplina_id' => 1],
            ['id' => 42, 'nome' => 'Planetas', 'disciplina_id' => 1],
            ['id' => 43, 'nome' => 'Mitologia grega', 'disciplina_id' => 1],
            ['id' => 44, 'nome' => 'Variedades de bananas', 'disciplina_id' => 1],
            ['id' => 45, 'nome' => 'Filmes da Disney', 'disciplina_id' => 1],
            ['id' => 46, 'nome' => 'Sinônimos de exposição', 'disciplina_id' => 1],
            ['id' => 47, 'nome' => 'Direitos humanos', 'disciplina_id' => 1],
            ['id' => 48, 'nome' => 'Árvores', 'disciplina_id' => 1],
            ['id' => 49, 'nome' => 'Bairros de São Paulo', 'disciplina_id' => 1],
            ['id' => 50, 'nome' => 'Letras gregas', 'disciplina_id' => 1],
            ['id' => 51, 'nome' => 'Peixes de aquário', 'disciplina_id' => 1],
            ['id' => 52, 'nome' => 'Emite sons de animais', 'disciplina_id' => 1],
            ['id' => 53, 'nome' => 'Personagens de Pulp Fiction', 'disciplina_id' => 1],
            ['id' => 54, 'nome' => 'Tubérculos', 'disciplina_id' => 1],
            ['id' => 55, 'nome' => 'Indumentária real', 'disciplina_id' => 1],
            ['id' => 56, 'nome' => 'Cargos auxiliares', 'disciplina_id' => 1],
            ['id' => 57, 'nome' => 'Cães de desenhos animados', 'disciplina_id' => 1],
            ['id' => 58, 'nome' => 'Jogos de baralho', 'disciplina_id' => 1],
            ['id' => 59, 'nome' => 'Marcas de alimentos', 'disciplina_id' => 1],
            ['id' => 60, 'nome' => 'Quem tem boa saúde', 'disciplina_id' => 1],
            ['id' => 61, 'nome' => 'Calma', 'disciplina_id' => 1],
            ['id' => 62, 'nome' => 'Tem no circo', 'disciplina_id' => 1],
            ['id' => 63, 'nome' => 'Quadriláteros', 'disciplina_id' => 1],
            ['id' => 64, 'nome' => 'Tipos de torresmo', 'disciplina_id' => 1],
            ['id' => 65, 'nome' => 'Símbolos dos naipes de baralho', 'disciplina_id' => 1],
            ['id' => 66, 'nome' => 'Unte', 'disciplina_id' => 1],
            ['id' => 67, 'nome' => 'Material escolar', 'disciplina_id' => 1],
            ['id' => 68, 'nome' => 'Tipos de tintas', 'disciplina_id' => 1],
            ['id' => 69, 'nome' => 'Funções da química inorgânica', 'disciplina_id' => 1],
            ['id' => 70, 'nome' => 'Cores', 'disciplina_id' => 1],
            ['id' => 71, 'nome' => 'Frutas', 'disciplina_id' => 1],
            ['id' => 72, 'nome' => 'Partes de uma jaqueta', 'disciplina_id' => 1],
            ['id' => 73, 'nome' => 'Tipos de vinagre', 'disciplina_id' => 1],
            ['id' => 74, 'nome' => 'Alimentos ricos em proteínas', 'disciplina_id' => 1],
            ['id' => 75, 'nome' => 'Produtos de higiene pessoal', 'disciplina_id' => 1],
            ['id' => 76, 'nome' => 'Bebidas quentes', 'disciplina_id' => 1],
            ['id' => 77, 'nome' => '___ em pó / Barra de ___', 'disciplina_id' => 1],
            ['id' => 78, 'nome' => 'Pé de ___', 'disciplina_id' => 1],
            ['id' => 79, 'nome' => 'Apoderação', 'disciplina_id' => 1],
            ['id' => 80, 'nome' => 'Pacote turístico', 'disciplina_id' => 1],
            ['id' => 81, 'nome' => 'Materiais elétricos', 'disciplina_id' => 1],
            ['id' => 82, 'nome' => 'Tabefe', 'disciplina_id' => 1],
            ['id' => 83, 'nome' => 'Estádio de futebol', 'disciplina_id' => 1],
            ['id' => 84, 'nome' => 'Guloseimas', 'disciplina_id' => 1],
            ['id' => 85, 'nome' => 'Produtos para pets', 'disciplina_id' => 1],
            ['id' => 86, 'nome' => 'Cidades Gaúchas', 'disciplina_id' => 1],
        ]);
    }
}
