<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class GruposSeeder extends Seeder {

    public function run(): void {
        DB::table('grupos')->insert([
            ['id' => 9, 'nome' => 'Personagens que usam verde', 'created_at' => null, 'updated_at' => null],
            ['id' => 10, 'nome' => 'Temperos', 'created_at' => null, 'updated_at' => null],
            ['id' => 11, 'nome' => 'Internet', 'created_at' => null, 'updated_at' => null],
            ['id' => 12, 'nome' => 'Meios de comunicação obsoletos', 'created_at' => null, 'updated_at' => null],
            ['id' => 13, 'nome' => 'Adjetivos relativos a frequência', 'created_at' => null, 'updated_at' => '2024-07-03 02:12:47'],
            ['id' => 14, 'nome' => 'Itens de papelaria', 'created_at' => null, 'updated_at' => null],
            ['id' => 15, 'nome' => 'Cosméticos labiais', 'created_at' => null, 'updated_at' => null],
            ['id' => 16, 'nome' => 'Carnaval', 'created_at' => null, 'updated_at' => null],
            ['id' => 17, 'nome' => 'Ritmos musicais', 'created_at' => null, 'updated_at' => null],
            ['id' => 18, 'nome' => 'Enorme', 'created_at' => null, 'updated_at' => null],
            ['id' => 19, 'nome' => 'Clássicos literários', 'created_at' => null, 'updated_at' => null],
            ['id' => 20, 'nome' => 'Roda (de) ___', 'created_at' => null, 'updated_at' => null],
            ['id' => 21, 'nome' => 'Usados no jardim', 'created_at' => null, 'updated_at' => null],
            ['id' => 22, 'nome' => 'Inteligente', 'created_at' => null, 'updated_at' => null],
            ['id' => 23, 'nome' => 'Pássaros', 'created_at' => null, 'updated_at' => null],
            ['id' => 24, 'nome' => 'Funções de modelos', 'created_at' => null, 'updated_at' => null],
            ['id' => 25, 'nome' => 'Típicos do Rio Grande do Sul', 'created_at' => null, 'updated_at' => null],
            ['id' => 26, 'nome' => 'Sobremesas geladas', 'created_at' => null, 'updated_at' => null],
            ['id' => 27, 'nome' => 'Apóstolos', 'created_at' => null, 'updated_at' => null],
            ['id' => 28, 'nome' => 'Olívias famosas', 'created_at' => null, 'updated_at' => null],
            ['id' => 29, 'nome' => 'Critérios para apuração do carnaval', 'created_at' => null, 'updated_at' => null],
            ['id' => 30, 'nome' => 'Marsupiais', 'created_at' => null, 'updated_at' => null],
            ['id' => 31, 'nome' => 'Instrumentos musicais', 'created_at' => null, 'updated_at' => null],
            ['id' => 32, 'nome' => 'Especiarias', 'created_at' => null, 'updated_at' => null],
            ['id' => 33, 'nome' => 'Reações comuns a picadas de insetos', 'created_at' => null, 'updated_at' => null],
            ['id' => 34, 'nome' => 'Órgãos do corpo humano', 'created_at' => null, 'updated_at' => null],
            ['id' => 35, 'nome' => 'Relacionados a sons', 'created_at' => null, 'updated_at' => null],
            ['id' => 36, 'nome' => 'Ratos de desenhos animados', 'created_at' => null, 'updated_at' => null],
            ['id' => 37, 'nome' => 'Quadrinhos', 'created_at' => null, 'updated_at' => null],
            ['id' => 38, 'nome' => 'Realizados no hospital', 'created_at' => null, 'updated_at' => null],
            ['id' => 39, 'nome' => 'Os/As três ___', 'created_at' => null, 'updated_at' => null],
            ['id' => 40, 'nome' => 'Procedimentos policiais', 'created_at' => null, 'updated_at' => null],
            ['id' => 41, 'nome' => 'Planetas', 'created_at' => null, 'updated_at' => null],
            ['id' => 42, 'nome' => 'Mitologia grega', 'created_at' => null, 'updated_at' => null],
            ['id' => 43, 'nome' => 'Variedades de bananas', 'created_at' => null, 'updated_at' => null],
            ['id' => 44, 'nome' => 'Filmes da Disney', 'created_at' => null, 'updated_at' => null],
            ['id' => 45, 'nome' => 'Sinônimos de exposição', 'created_at' => null, 'updated_at' => null],
            ['id' => 46, 'nome' => 'Direitos humanos', 'created_at' => null, 'updated_at' => null],
            ['id' => 47, 'nome' => 'Árvores', 'created_at' => null, 'updated_at' => null],
            ['id' => 48, 'nome' => 'Bairros de São Paulo', 'created_at' => null, 'updated_at' => null],
            ['id' => 49, 'nome' => 'Letras gregas', 'created_at' => null, 'updated_at' => null],
            ['id' => 50, 'nome' => 'Peixes de aquário', 'created_at' => null, 'updated_at' => null],
            ['id' => 51, 'nome' => 'Emite sons de animais', 'created_at' => null, 'updated_at' => null],
            ['id' => 52, 'nome' => 'Personagens de Pulp Fiction', 'created_at' => null, 'updated_at' => null],
            ['id' => 53, 'nome' => 'Tubérculos', 'created_at' => null, 'updated_at' => null],
            ['id' => 54, 'nome' => 'Indumentária real', 'created_at' => null, 'updated_at' => null],
            ['id' => 55, 'nome' => 'Cargos auxiliares', 'created_at' => null, 'updated_at' => null],
            ['id' => 56, 'nome' => 'Cães de desenhos animados', 'created_at' => null, 'updated_at' => null],
            ['id' => 57, 'nome' => 'Jogos de baralho', 'created_at' => null, 'updated_at' => null],
            ['id' => 58, 'nome' => 'Marcas de alimentos', 'created_at' => null, 'updated_at' => null],
            ['id' => 59, 'nome' => 'Quem tem boa saúde', 'created_at' => null, 'updated_at' => null],
            ['id' => 60, 'nome' => 'Calma', 'created_at' => null, 'updated_at' => null],
            ['id' => 61, 'nome' => 'Fontes de energia', 'created_at' => null, 'updated_at' => null],
            ['id' => 62, 'nome' => 'Participantes num processo judicial', 'created_at' => null, 'updated_at' => null],
            ['id' => 63, 'nome' => 'Notas musicais', 'created_at' => null, 'updated_at' => null],
            ['id' => 64, 'nome' => 'Advérbios de lugar', 'created_at' => null, 'updated_at' => null],
            ['id' => 65, 'nome' => 'Fórmula 1', 'created_at' => null, 'updated_at' => null],
            ['id' => 66, 'nome' => '__ vermelho', 'created_at' => null, 'updated_at' => null],
            ['id' => 67, 'nome' => 'Chocolates da Garoto 1', 'created_at' => null, 'updated_at' => null],
            ['id' => 68, 'nome' => 'Ilhas Famosas', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 69, 'nome' => 'Enfeite', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 70, 'nome' => 'Reinos Biológicos', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 71, 'nome' => 'Sinônimos de Vínculo', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 72, 'nome' => 'RPG', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 73, 'nome' => 'Sociólogos', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 75, 'nome' => 'Receita de quindim', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 76, 'nome' => 'Aquele que comanda', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' => 77, 'nome' => 'Aves', 'created_at' => NULL, 'updated_at' => NULL],
            ['id' =>  78, 'nome' => 'Espécies de Pinguins', 'created_at' => NULL, 'updated_at' => NULL],
        ]);
    }
}
