<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class GruposPalavrasSeeder extends Seeder {
    /**
     * Run the database seeds.
     */
    public function run(): void {
        DB::table('grupos_palavras')->insert([

            ['grupo_id' => 9, 'palavra_id' => 25, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 9, 'palavra_id' => 26, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 9, 'palavra_id' => 27, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 9, 'palavra_id' => 28, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 10, 'palavra_id' => 29, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 10, 'palavra_id' => 30, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 10, 'palavra_id' => 31, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 10, 'palavra_id' => 32, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 11, 'palavra_id' => 33, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 11, 'palavra_id' => 34, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 11, 'palavra_id' => 35, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 11, 'palavra_id' => 36, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 12, 'palavra_id' => 37, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 12, 'palavra_id' => 38, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 12, 'palavra_id' => 39, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 12, 'palavra_id' => 40, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 13, 'palavra_id' => 41, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 13, 'palavra_id' => 42, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 13, 'palavra_id' => 43, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 13, 'palavra_id' => 44, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 14, 'palavra_id' => 45, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 14, 'palavra_id' => 46, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 14, 'palavra_id' => 47, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 14, 'palavra_id' => 48, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 15, 'palavra_id' => 49, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 15, 'palavra_id' => 50, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 15, 'palavra_id' => 51, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 15, 'palavra_id' => 52, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 16, 'palavra_id' => 53, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 16, 'palavra_id' => 54, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 16, 'palavra_id' => 55, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 16, 'palavra_id' => 56, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 17, 'palavra_id' => 57, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 17, 'palavra_id' => 58, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 17, 'palavra_id' => 59, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 17, 'palavra_id' => 60, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 18, 'palavra_id' => 61, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 18, 'palavra_id' => 62, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 18, 'palavra_id' => 63, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 18, 'palavra_id' => 64, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 19, 'palavra_id' => 65, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 19, 'palavra_id' => 66, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 19, 'palavra_id' => 67, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 19, 'palavra_id' => 68, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 20, 'palavra_id' => 69, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 20, 'palavra_id' => 70, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 20, 'palavra_id' => 71, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 20, 'palavra_id' => 72, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 21, 'palavra_id' => 73, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 21, 'palavra_id' => 74, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 21, 'palavra_id' => 75, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 21, 'palavra_id' => 76, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 22, 'palavra_id' => 77, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 22, 'palavra_id' => 78, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 22, 'palavra_id' => 79, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 22, 'palavra_id' => 80, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 23, 'palavra_id' => 81, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 23, 'palavra_id' => 82, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 23, 'palavra_id' => 83, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 23, 'palavra_id' => 84, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 24, 'palavra_id' => 85, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 24, 'palavra_id' => 86, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 24, 'palavra_id' => 87, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 24, 'palavra_id' => 88, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 25, 'palavra_id' => 89, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 25, 'palavra_id' => 90, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 25, 'palavra_id' => 91, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 25, 'palavra_id' => 92, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 26, 'palavra_id' => 93, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 26, 'palavra_id' => 94, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 26, 'palavra_id' => 95, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 26, 'palavra_id' => 96, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 27, 'palavra_id' => 97, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 27, 'palavra_id' => 98, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 27, 'palavra_id' => 99, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 27, 'palavra_id' => 100, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 28, 'palavra_id' => 101, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 28, 'palavra_id' => 102, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 28, 'palavra_id' => 103, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 28, 'palavra_id' => 104, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 29, 'palavra_id' => 105, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 29, 'palavra_id' => 106, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 29, 'palavra_id' => 107, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 29, 'palavra_id' => 108, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 30, 'palavra_id' => 109, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 30, 'palavra_id' => 110, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 30, 'palavra_id' => 111, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 30, 'palavra_id' => 112, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 31, 'palavra_id' => 113, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 31, 'palavra_id' => 114, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 31, 'palavra_id' => 115, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 31, 'palavra_id' => 116, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 32, 'palavra_id' => 117, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 32, 'palavra_id' => 118, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 32, 'palavra_id' => 119, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 32, 'palavra_id' => 120, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 33, 'palavra_id' => 121, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 33, 'palavra_id' => 122, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 33, 'palavra_id' => 123, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 33, 'palavra_id' => 124, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 34, 'palavra_id' => 125, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 34, 'palavra_id' => 126, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 34, 'palavra_id' => 127, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 34, 'palavra_id' => 128, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 35, 'palavra_id' => 129, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 35, 'palavra_id' => 130, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 35, 'palavra_id' => 131, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 35, 'palavra_id' => 132, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 36, 'palavra_id' => 133, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 36, 'palavra_id' => 134, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 36, 'palavra_id' => 135, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 36, 'palavra_id' => 136, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 37, 'palavra_id' => 137, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 37, 'palavra_id' => 138, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 37, 'palavra_id' => 139, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 37, 'palavra_id' => 140, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 38, 'palavra_id' => 141, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 38, 'palavra_id' => 142, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 38, 'palavra_id' => 143, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 38, 'palavra_id' => 144, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 39, 'palavra_id' => 145, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 39, 'palavra_id' => 146, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 39, 'palavra_id' => 147, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 39, 'palavra_id' => 148, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 40, 'palavra_id' => 149, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 40, 'palavra_id' => 150, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 40, 'palavra_id' => 151, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 40, 'palavra_id' => 152, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 41, 'palavra_id' => 153, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 41, 'palavra_id' => 154, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 41, 'palavra_id' => 155, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 41, 'palavra_id' => 156, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 42, 'palavra_id' => 157, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 42, 'palavra_id' => 158, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 42, 'palavra_id' => 159, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 42, 'palavra_id' => 160, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 43, 'palavra_id' => 161, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 43, 'palavra_id' => 162, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 43, 'palavra_id' => 163, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 43, 'palavra_id' => 164, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 44, 'palavra_id' => 165, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 44, 'palavra_id' => 166, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 44, 'palavra_id' => 167, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 44, 'palavra_id' => 168, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 45, 'palavra_id' => 169, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 45, 'palavra_id' => 170, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 45, 'palavra_id' => 171, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 45, 'palavra_id' => 172, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 46, 'palavra_id' => 173, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 46, 'palavra_id' => 174, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 46, 'palavra_id' => 175, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 46, 'palavra_id' => 176, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 47, 'palavra_id' => 177, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 47, 'palavra_id' => 178, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 47, 'palavra_id' => 179, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 47, 'palavra_id' => 180, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 48, 'palavra_id' => 181, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 48, 'palavra_id' => 182, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 48, 'palavra_id' => 183, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 48, 'palavra_id' => 184, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 49, 'palavra_id' => 185, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 49, 'palavra_id' => 186, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 49, 'palavra_id' => 187, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 49, 'palavra_id' => 188, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 50, 'palavra_id' => 189, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 50, 'palavra_id' => 190, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 50, 'palavra_id' => 191, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 50, 'palavra_id' => 192, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 51, 'palavra_id' => 193, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 51, 'palavra_id' => 194, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 51, 'palavra_id' => 195, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 51, 'palavra_id' => 196, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 52, 'palavra_id' => 197, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 52, 'palavra_id' => 198, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 52, 'palavra_id' => 199, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 52, 'palavra_id' => 200, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 53, 'palavra_id' => 201, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 53, 'palavra_id' => 202, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 53, 'palavra_id' => 203, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 53, 'palavra_id' => 204, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 54, 'palavra_id' => 205, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 54, 'palavra_id' => 206, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 54, 'palavra_id' => 207, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 54, 'palavra_id' => 208, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 55, 'palavra_id' => 209, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 55, 'palavra_id' => 210, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 55, 'palavra_id' => 211, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 55, 'palavra_id' => 212, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 56, 'palavra_id' => 213, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 56, 'palavra_id' => 214, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 56, 'palavra_id' => 215, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 56, 'palavra_id' => 216, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 57, 'palavra_id' => 217, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 57, 'palavra_id' => 218, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 57, 'palavra_id' => 219, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 57, 'palavra_id' => 220, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 58, 'palavra_id' => 221, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 58, 'palavra_id' => 222, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 58, 'palavra_id' => 223, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 58, 'palavra_id' => 224, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 59, 'palavra_id' => 225, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 59, 'palavra_id' => 226, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 59, 'palavra_id' => 227, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 59, 'palavra_id' => 228, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 60, 'palavra_id' => 229, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 60, 'palavra_id' => 230, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 60, 'palavra_id' => 231, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 60, 'palavra_id' => 232, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 61, 'palavra_id' => 233, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 61, 'palavra_id' => 234, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 61, 'palavra_id' => 235, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 61, 'palavra_id' => 236, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 62, 'palavra_id' => 237, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 62, 'palavra_id' => 238, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 62, 'palavra_id' => 239, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 62, 'palavra_id' => 240, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 63, 'palavra_id' => 241, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 63, 'palavra_id' => 242, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 63, 'palavra_id' => 243, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 63, 'palavra_id' => 244, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 64, 'palavra_id' => 245, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 64, 'palavra_id' => 246, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 64, 'palavra_id' => 247, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' => 64, 'palavra_id' => 248, 'created_at' => NULL, 'updated_at' => NULL],
            ['grupo_id' =>  72, 'palavra_id' =>  404, 'created_at' => '2024-05-23 14:27:10', 'updated_at' => '2024-05-23 14:27:10'],
            ['grupo_id' =>  72, 'palavra_id' =>  403, 'created_at' => '2024-05-23 14:28:02', 'updated_at' => '2024-05-23 14:28:02'],
            ['grupo_id' =>  72, 'palavra_id' =>  402, 'created_at' => '2024-05-23 14:28:37', 'updated_at' => '2024-05-23 14:28:37'],
            ['grupo_id' =>  72, 'palavra_id' =>  401, 'created_at' => '2024-05-23 14:28:53', 'updated_at' => '2024-05-23 14:28:53'],
            ['grupo_id' =>  71, 'palavra_id' =>  400, 'created_at' => '2024-05-23 14:29:19', 'updated_at' => '2024-05-23 14:29:19'],
            ['grupo_id' =>  71, 'palavra_id' =>  399, 'created_at' => '2024-05-23 14:29:44', 'updated_at' => '2024-05-23 14:29:44'],
            ['grupo_id' =>  72, 'palavra_id' =>  28, 'created_at' => '2024-05-23 14:29:54', 'updated_at' => '2024-05-23 14:29:54'],
            ['grupo_id' =>  71, 'palavra_id' =>  398, 'created_at' => '2024-05-23 14:33:26', 'updated_at' => '2024-05-23 14:33:26'],
            ['grupo_id' =>  71, 'palavra_id' =>  397, 'created_at' => '2024-05-23 14:34:11', 'updated_at' => '2024-05-23 14:34:11'],
            ['grupo_id' =>  70, 'palavra_id' =>  396, 'created_at' => '2024-05-23 14:34:35', 'updated_at' => '2024-05-23 14:34:35'],
            ['grupo_id' =>  70, 'palavra_id' =>  395, 'created_at' => '2024-05-23 14:34:42', 'updated_at' => '2024-05-23 14:34:42'],
            ['grupo_id' =>  70, 'palavra_id' =>  394, 'created_at' => '2024-05-23 14:34:47', 'updated_at' => '2024-05-23 14:34:47'],
            ['grupo_id' =>  70, 'palavra_id' =>  393, 'created_at' => '2024-05-23 14:34:53', 'updated_at' => '2024-05-23 14:34:53'],
            ['grupo_id' =>  69, 'palavra_id' =>  392, 'created_at' => '2024-05-23 14:35:17', 'updated_at' => '2024-05-23 14:35:17'],
            ['grupo_id' =>  69, 'palavra_id' =>  391, 'created_at' => '2024-05-23 14:35:23', 'updated_at' => '2024-05-23 14:35:23'],
            ['grupo_id' =>  69, 'palavra_id' =>  390, 'created_at' => '2024-05-23 14:35:31', 'updated_at' => '2024-05-23 14:35:31'],
            ['grupo_id' =>  69, 'palavra_id' =>  389, 'created_at' => '2024-05-23 14:35:51', 'updated_at' => '2024-05-23 14:35:51'],
            ['grupo_id' =>  73, 'palavra_id' =>  389, 'created_at' => '2024-05-23 14:36:18', 'updated_at' => '2024-05-23 14:36:18'],
        ]);
    }
}
